helm/helm-classic

.travis.yml, Makefile, test/config.sh, test/lib.sh, test/test-charts
Currently the makefile needs some love in other places (why it's commented out inside of the `make test-charts` logic), but this is my idea behind how we test PRs for charts:
If it's a PR, we see what charts have changed and then execute 
```
helm install <chart>
helm test <chart>
helm uninstall <chart>
```
(example: https://travis-ci.org/sgoings/helm/builds/86681185)
If it's master we just run a set of default chart installs (overrideable via TEST_CHARTS env)
Related #4
=> feat(test): add ci test infrastructure scaffolding

docs/architecture.md, helm/action/create.go, helm/action/edit.go, helm/action/edit_test.go, helm/helm.go, helm/testdata/charts/redis/Chart.yaml, helm/testdata/charts/redis/manifests/redis-pod.yaml, skel/Chart.yaml, skel/README.md, skel/manifests/example-pod.yaml
This PR adds `helm create` and `helm edit` commands which make for a nice contributor workflow.
Note a lot of this code will have to be refactored once we move chart serialization/deserialization into the `model` package.
Example of `helm create`:
```console
$ helm create mychart
Copying /Users/gabriel/workspace/src/github.com/deis/helm/skel
Copying /Users/gabriel/workspace/src/github.com/deis/helm/skel/Chart.yaml
Copying /Users/gabriel/workspace/src/github.com/deis/helm/skel/README.md
Copying /Users/gabriel/workspace/src/github.com/deis/helm/skel/manifests
Copying /Users/gabriel/workspace/src/github.com/deis/helm/skel/manifests/example-pod.yaml
```
Example of `helm edit` which opens in `$EDITOR` and saves the results:
```console
$ helm edit mychart
--- # Chart.yaml
name: example-pod-2 …
```
=> feat(*): add create and edit commands

README.md
@technosophos suggested a logo to indicate that certain deis/* umbrella projects are considered in progress and don't necessarily follow the same process as deis/deis. Here is a simple one.
=> docs(README.md): clarify that helm is a WIP

helm/action/action.go, helm/action/create.go, helm/action/edit.go, helm/action/fetch.go, helm/action/info.go, helm/action/install.go, helm/action/list.go, helm/action/update.go
* `WorkDirChartPath` is redundant
* refactor globals to `action.go`
=> ref(action): s/WorkDirChartPath/WorkspaceChartPath/

Makefile, glide-full.yaml
Earlier versions of Glide did not flatten dependencies, which makes
k8s about 2G of data, and causes some conflicts. This is a temporary
fix.
=> fix(*): adds temporary fix until Glide 0.7

README.md
README now notes that a Go developer needs Glide. And the Makefile
clean target now removes the right binary.
Addresses #52
=> fix(*): updated README and changed clean

helm/action/update.go
During update, we now check and create cache and workspace dirs
if they don't exist.
Addresses #40, fixes the same problem as reported in #67, unblocks
issue #58.
=> fix(*): create cache and workspace directories

glide.yaml
Needed to manuall `glide get` this dependency with a clean `$GOPATH` and a `glide up`.
Fixes:
```
helm [master]$ make build
go build -o helm.bin -ldflags "-X main.version=" helm/helm.go
vendor/k8s.io/kubernetes/pkg/api/resource/quantity.go:27:2: cannot find package "speter.net/go/exp/math/dec/inf" in any of:
/Users/jhansen/p/go/src/github.com/deis/helm/vendor/speter.net/go/exp/math/dec/inf (vendor tree)
/usr/local/Cellar/go/1.5.1/libexec/src/speter.net/go/exp/math/dec/inf (from $GOROOT)
/Users/jhansen/p/go/src/speter.net/go/exp/math/dec/inf (from $GOPATH)
make: *** [build] Error 1
```
=> bug(deps) speter.net/go/exp/math/dec/inf

helm/action/install.go, helm/helm.go
This supports an alternative installation process for installing
a single chart from a specific location into the local workspace,
and then pushing it into Kubernetes.
See issue #47.
=> feat(*): add --chart-path to install

skel/Chart.yaml, skel/README.md, skel/manifests/example-pod.yaml
Make the skeleton more generic. Prompt for the things we would like to see.
Might also be a good opportunity to expand the skeleton to include a Service definition, so we can explain our approach to labels in situ.
=> doc(skel) make the skeleton Chart generic

.gitignore, .travis.yml, Makefile, ci/bintray-template.json
If the master branch is changed, published binaries end up in the helm-ci repository: https://bintray.com/deis/helm-ci/helm/
If it's a release (has a tag), the binaries will be pushed to https://bintray.com/deis/helm/helm/ with the version being the tag name.
No binaries are published on pull requests.
Fixes #93
=> feat(ci): publish binaries to Bintray

mkdocs.yml
According to the OED, 'nameing' is an authoritatively quoted spelling from 1566:
*J. Knox Hist. Reformation in Wks. (1846) I. 431*
> "To command free Browchis to cheise Provestis and officiaris of our nameing."
and as recently as 1678:
*Grant Coal Shillings to Duke of Richmond 18 Dec. in J. Brand Hist. & Antiq. Newcastle (1789) II. 671*
> "The..misnameing or not nameing of any demise or grant."
**and** by no less an authority than Milton! in 1670:
*Milton Hist. Brit. iv. 182*
> "So different they often are one from another, both in timeing and in nameing."
It would thus be rash to call "nameing" a typo; but it's probably best to reconcile the reference in mkdocs.yml with the actual filename by adopting the contemporary orthographic idiom.
=> chore(*): filename mismatch in mkdocs.yml

helm/helm.go
The following changes were made to helm.go:
- All small command functions were collapsed back into the app
command objects. This seems to be much easier to work with.
- Descriptions were added to all commands that required more help
text.
- Bash/Zsh autocompletion was enabled. Users still need to source
the requisite files into their shell, though.
=> chore(*): clean up the helm.go file

helm/action/remove.go, helm/action/remove_test.go, helm/helm.go
`helm remove [chart]` removes a chart from the
workspace directory. This resolves issue #55.
=> feat(remove) helm remove command

helm/helm.go
Previously, users would see a confusing "No help topic for 'command'"
when trying to run an invalid command. Now, they see an appropriate
message and the usage text.
fixes #128
=> feat(helm): show help text for invalid commands

.travis.yml
Leverage the travis cache system to speed up dependency handling.
The first time through the `vendor/` directory will be populated and the slower speed. After the first pass it will be cached and only updates to the packages will be pulled down. This should provide a dramatic speedup. In my own testing of helm I saw it take ~20s to handle dependencies in `vendor/` with a warm cache.
=> test(travis): speed up glide pkg handling

helm/log/log.go
This gives better output from the Git commands, including catching full Git errors when they happen.
=> feat(*): add log.Logger and set Git to write to it

README.md
Glide has a release with the needed features (0.7.0) that is
available in homebrew.
=> docs(README): removed glide version warning

action/fetch.go
This fixes a bug where `helm fetch alpine mypod` would fail.
=> fix(fetch): use target name correctly

README.md, action/fetch.go, action/install.go, action/search.go, action/uninstall.go, action/update.go
This PR is an effort to streamline CLI output following a _less is more_ strategy:
* Move debug statements to `log.Debug`
* Move `log.Info` statement into public functions so they're easier to find/change
* Be more consistent with Helm terminology like "cache" and "workspace"
* Update the README with actual CLI output
There is definitely more we need to do here, but this mostly covers the basic user workflow. Closes #116.
=> Cleanup Helm CLI output

action/create.go
This fixes a bug in YAML formatting that would manifest during:
```
$ helm create mychart
$ helm install mychart
<yaml error>
```
=> fix(create): fix yaml formatting in skeleton manifest

action/create_test.go
`create_test.go` got left behind in #143 refactoring. This moves it to where it will be run and corrects its expected output. From [Travis CI](https://travis-ci.org/deis/helm/builds/89099840):
```console
$ make test
go test -v ./. ./manifest ./action ./log ./chart ./dependency
...
=== RUN   TestCreate
---> Created chart in /tmp/helm_home044239326/workspace/charts/mychart
--- PASS: TestCreate (0.00s)
=== RUN   TestListChart
...
```
=> fix(action): restore "helm create" tests

glide-full.yaml, glide.yaml
this was quite simple to do. `glide up` now works, but we need to get `make bootstrap` working again as well as documenting how to re-generate glide-full.yaml so other devs know how to do this in the future. Ping @technosophos
=> fix(glide): add deis/pkg to glide.yaml

MAINTAINERS.md
The Helm captains didn't think a BDFL was necessary, and wanted to clarify LGTM and contributing details, and I was volunteered to write it down or be keelhauled. Some of the language in the Deis version of this file didn't seem appropriate, so I rewrote bits.
Refs #163.
=> docs(MAINTAINERS.md): describe Helm steering process

action/fetch.go
I didn't see ns declared/used anywhere in this function, so I took out the line in the doc.
=> fix(fetch): refactor doc for fetch function

.travis.yml, Makefile, config/config.go
Adds a `make test-style` target similar to deis/deis. Runs `gofmt`, `golint`, and `go vet`. See also #113.
TODO:
=> add linters to test-style target

helm.go
This is for shell scripts that need to determine the location of
Helm's home directory.
Example: 
```
cd $(helm home)
```
=> feat(*): add 'home' subcommand

.travis.yml
It shouldn't be necessary to build [`glide`](https://github.com/Masterminds/glide/releases) from source each time we run tests. This has Travis CI download and untar the binary as is done in [deis/workflow](https://github.com/deis/workflow).
=> ref(.travis.yml): use glide binary releases

.travis.yml, README.md
See https://github.com/Masterminds/glide/releases/tag/0.7.2
I had talked with @technosophos about the annoying re-ordering bug, so this seems like a fix we want.
~~(Note that Homebrew still has only glide 0.7.1 as of this morning.)~~ Updated in `brew` now as well.
=> chore(.travis.yml): update glide to 0.7.2

glide-full.yaml
This change resolves issue #207.
=> ref(glide-full) pin to specific ver of go-github

release/latest.go
Important for commands like `helm update`. Replaces #232 in order to get CI to run on this PR.
=> fix(release): update helm owner to helm org

action/remove.go, action/remove_test.go, helm.go
Fixes: https://github.com/helm/helm/issues/183
Introduces a `--force` option on `helm remove` to remove charts from workspace that are installed.
TODO
=> fix(remove): prevent removing installed charts from workspace

helm.go
Not long ago @bacongobbler  rightly noted that the default version should
not be 0.0.1, but 0.1.0 (following SemVer 2). I added the -unstable flag
to distinguish this from an actually tagged release.
=> chore(helm): set default version

action/remove.go, helm.go, log/log.go
This causes helm to always exit(1) when `log.Err()` is called. Even if `log.Err()` is called and helm continues.
=> feat(*): Exit(1) when log.Err is called

action/edit.go, action/edit_test.go
Fixes: https://github.com/helm/helm/issues/286
This PR changes the editing workflow by opening the chart directory in `$EDITOR` rather than generating a single temp file for all manifests.
=> bug(edit): make editor open chart folder directly

action/lint.go, action/lint_test.go, validation/validation.go
ChartValidation struct keeps track of a linting instance. Validation struct keeps track of a validation and its
dependent validations as well. This will help us link validations in a proper format and be able to more easily see and define validations rather than rely on logic nested in loops and arbitrary functions.
=> ref(lint): cleaner lint validations

README.md
Doing `curl -s https://get.helm.sh | sh` results in `sh: 13: set: Illegal option -o pipefail`. I guess the installation script is not POSIX-compliant.
=> Use bash to install helm

.travis.yml, glide.lock, glide.yaml
- `glide up` run with 0.9.0 that walks the import tree rather than
the filesystem tree. Pulls just the 36 dependencies in the tree.
- Removes travic ci caching. The number of packages being
is small enough fetching them should be faster than copying from
the travis cache.
- The glide install run Make bootstrap should be backwards
compatible to glide 0.8.3.
The output of `glide up` is at https://gist.github.com/mattfarina/009fad1cfbaccdce7aca
=> ref(glide): Using glide 0.9.0 new import resolver

action/template.go
Templates could've only been generated using data from files and the output had to be written to a file to.
GenerateTemplate now allows one to generate templates from and to io.Reader and io.Writer objects respectively.
This can come in handy in situations where the data is generated/manipulated dynamically (say, through a web ui).
=> Decoupled templating functionality from file IO

glide.lock, glide.yaml
This is already the version in the lock, but we need to make this
explicit.
=> fix(vendor): set sprig to 1.2.0.

docs/awesome.md
YAML needs boolean values to be quoted, so this improves the suggestion about adding `scalable: "false"` to a chart. This caused minor confusion in helm/charts#75.
=> docs(awesome.md): quote boolean YAML value

mkdocs.yml
This pr fixes issue #400 by adding missing doc files to the mkdocs.yml used to build the readthedocs site.
=> Fix #400 - add docs to readthedocs mkdocs.yml

.travis.yml, glide.lock, glide.yaml
- Removes appengine ignore which is special case handled by glide
- Re-resolves the tree for 2 fewer dependencies that were not
in use
- Updates Travis CI to use the latest release
=> ref(glide): Update to glide 0.9.1

action/install.go, action/install_test.go, cli/install.go
This adds the `-g` and `-x` flags to `helm install`.
To run generators: `helm install -g CHART`
To exclude the manifests directory: `helm install -g -x manifests CHART`
=> feat(install): add -g to run generator

action/lint.go
Added maximum Metadata.name length (=24) constraint
Closes #412
=> fix(action/lint.go): Chart validation

codec/object.go, generator/generator.go, search/search.go, search/search_test.go, validation/validation.go
Noticed some easy fixes on https://goreportcard.com/report/github.com/helm/helm so I addressed most of them:
* guranteed -> guaranteed
* `gofmt -w -s search/search_test.go`
* Add missing comments, or fix golint comment format "methodName ..."
* Address golint unnecessary type validation
=> Fix typos and run gofmt

glide.lock, glide.yaml
The semver package is looking make a 2.x release so it's worth moving to release versions rather than following the tip of master. In this PR the semver and vcs packages will use the latest 1.x release.
=> feat(glide.yaml): Use releases for semver and vcs packages

glide.lock, glide.yaml
[codegangsta/cli](https://github.com/codegangsta/cli) fixed an issue that caused a panic if commands such as `helm help` were piped to another command. That package doesn't do proper semver releases, so this references a [current SHA](https://github.com/codegangsta/cli/commit/71f57d300dd6a780ac1856c005c4b518cfd498ec).
Closes #387.
cc: @technosophos
=> fix(glide.yaml): update cli support package

glide.lock, glide.yaml
commit e6494bc7e81206ba6db404d2fd96500ffc453407 contains a new function called
`genPrivateKey` which will allow us to generate private keys on the fly with `helm generate`.
=> chore(glide): bump Masterminds/sprig to 2.2.0

action/lint.go
After correcting this documentation comment, `golint` runs quietly once again.
=> style(action/lint.go): silence golint warning

action/generate.go, action/template.go, action/template_test.go
pass the force flag to all the template commands because some times the helm template commands may be executed as part of script which is executed using the helm generate
=> fix(force): pass the force flag to all the tpl commands

CONTRIBUTING.md, MAINTAINERS.md, README.md, docs/README.md, docs/architecture.md, docs/authoring_charts.md, docs/awesome.md, docs/chart_tables.md, docs/generate-and-template.md, docs/index.md, docs/modeling_services.md, docs/plugins.md, docs/using_labels.md, docs/workspace.md, plugins/example/README.md, plugins/sec/README.md
Fixes #452 
This reflects many changes that have not been implemented yet, but I'd prefer to not be submitting a mammoth PR.  If this means the docs at the head of the master branch are temporarily incorrect, I believe that is acceptable.  I have removed the readthedocs webhook from this repository that so that these changes will _not_ propagate to the _original_ (not to be conflated with "classic") helm docs at http://helm.readthedocs.io/en/latest/
The existing docs were also a bit stale, so some corrections were also made for accuracy.  For instance, the documented layout of the `helmc home` dir was all wrong.
=> doc(*): Update docs for helm-classic

Makefile
This error somehow made it past code reviews for #445.
This snippet of code, once upon a time was at the very top of the Makefile.  #445 initially meant to remove that.  @mboersma said it should stay and @chaitanyaenr agreed to that, but somehow, it _moved_ down to here where it broke the `dev` target (which allows contributors to step interactively into the containerized development environment).
As for where this snippet actually belongs... the whole point of the containerized development environment is that no one should _need_ Go installed and set up on their local machine-- and this would include not needing to have the `GOPATH` env var defined.
What I have done in this PR is _moved_ this check to the `native-build` target, which is the target that contributors can _optionally_ …
=> fix(Makefile): Fix error in dev target

action/generate.go, action/plugin.go, cli/helm.go, cli/update.go, dependency/dependency.go, plugins/example/helm-example.go, test/helm.go, util/helm.go
=> ref(*): Use HELMC_HOME instead of HELM_HOME

Makefile, glide.lock
`make bootstrap` kept failing for me, so I took out the big hammer and updated `go` and `glide` and regenerated the dependency lock file. Works For Me&trade; now, although honestly the original errors may have been transient and not specifically fixed by this. 😄
=> chore(*): update go to 1.6.2 and glide to 0.10.2

README.md, action/action.go, action/doc.go, action/doctor.go, action/edit.go, action/fetch.go, action/update.go, action/update_test.go, cli/create.go, cli/doctor.go, cli/edit.go, cli/fetch.go, cli/generate.go, cli/helm.go, cli/home.go, cli/install.go, cli/lint_test.go, cli/template.go, cli/update.go, codec/object.go, config/config.go, docs/README.md, docs/index.md, release/latest.go, search/search.go, util/helm.go
Fixes #469
This PR updates help, output messages, comments, and a few other errant, outdated occurrences of "helm" or "Helm" with "helmc" and "Helm Classic" wherever appropriate.
=> chore(*): Update comments and help strings for Helm Classic

README.md, docs/index.md
Fixes #463 
Explains the original Helm -> Helm Classic rebranding and steps for users of the original Helm to follow to complete the migration.
=> doc(migration): Add migration docs

action/action_test.go, action/install.go, action/uninstall.go, action/uninstall_test.go, docs/awesome.md, kubectl/apply.go, kubectl/apply_test.go, kubectl/kubectl.go, manifest/manifest.go, manifest/manifest_test.go, testdata/charts/keep/Chart.yaml, testdata/charts/keep/manifests/keep-ns.yaml, testdata/service-keep.json, testdata/service.json
This modifies `helmc` to treat manifests with a `helm-keep: "true"` annotation specially:
- On `install`, they are treated with `kubectl apply` rather than `kubectl create`
- On `uninstall`, they are skipped with a warning
This behavior should allow crucial manifests to persist over a `helmc uninstall <version_one> && helmc install <version_two>` upgrade scenario. In particular, an externally routed service can be annotated with `helm-keep` so that DNS does not have to be recreated for its `LoadBalancer`.
Closes #465.
=> feat(manifest|action): handle "helm-keep" annotation

action/install.go, action/remove_test.go, testdata/charts/kitchensink/manifests/sink-limits.yaml
The marshalAndCreate method was always returning empty JSON for unknown manifest types.
Fixes #477.
=> fix(install): let VersionedObject marshal its own JSON

action/install.go, action/remove_test.go, chart/chart_test.go, codec/object.go, glide.lock, glide.yaml, testdata/charts/kitchensink/manifests/sink-configmap.yaml
Also updates the k8s `glide` dependency to 1.2.4 so `v1.ConfigMap` is visible.
Closes #461.
See also #462.
=> feat(action): add ConfigMap install ordering

Makefile
Includes the go 1.7 toolchain. See https://tip.golang.org/doc/go1.7
I've been testing macOS Sierra developer betas, and both compiling and running `helmc` caused frequent panics until I started using go 1.7. So this should be some future-proofing for good ol' Helm classic.
=> chore(Makefile): update to go-dev 0.17.0
