helm/helm-classic

helm/action/fetch.go
helm/action/install.go
helm/action/list.go
helm/action/print.go
helm/action/search.go
helm/action/update.go
helm/helm.go

fix(*): mirror cache in workspace

---

helm/action/build.go
helm/action/fetch.go
helm/action/install.go
helm/action/list.go
helm/action/search.go
helm/action/update.go
helm/helm.go
helm/log/log.go

Prevents name conflicts with info command

ref(log): refactor logging to package

---

charts/alpine/manifests/alpine-pod.yaml
helm/action/doc.go
helm/action/install.go
helm/action/uninstall.go
helm/helm.go
helm/log/log.go

This adds a very basic version of install. We still need to make the actual call to Kubectl a little more intelligent, but this will be useful for testing.

feat(*): add basic install

---

DCO

changed to current Linux Foundation address

update LF address

---

charts/alpine/manifests/alpine-pod.yaml
helm/manifest/manifest.go
helm/manifest/manifest_test.go

This provides the basic utilities for working with Kubernetes manifests.

feat(*): support for parsing manifest files

---

Makefile
helm/manifest/manifest_test.go
helm/testdata/charts/kitchensink/Chart.yaml
helm/testdata/charts/kitchensink/manifests/sink-daemonset.yaml-wait-till-1.1
helm/testdata/charts/kitchensink/manifests/sink-namespace.yaml
helm/testdata/charts/kitchensink/manifests/sink-pod.yaml
helm/testdata/charts/kitchensink/manifests/sink-rc.yaml
helm/testdata/charts/kitchensink/manifests/sink-secret.yaml
helm/testdata/charts/kitchensink/manifests/sink-volume.yaml

This commit just adds a bunch of testing data and fixes a bug in the Makefile.

fix(*): improve the test data

---

helm/action/install.go

fix(install): don't supply default namespace

---

Makefile
README.md
glide.yaml
helm/action/info.go
helm/action/install.go
helm/action/list.go
helm/action/search.go
helm/action/target.go
helm/action/uninstall.go
helm/helm.go
helm/manifest/manifest.go
helm/manifest/manifest_test.go
helm/model/chart.go
helm/model/chart_test.go
helm/model/chartfile.go
helm/testdata/charts/kitchensink/Chart.yaml
helm/testdata/charts/kitchensink/annoy_testers/README.md
helm/testdata/charts/kitchensink/annoy_testers/broken.yaml
helm/testdata/charts/kitchensink/manifests/foo.json
helm/testdata/charts/kitchensink/manifests/nested/nested-pod.yaml
helm/testdata/charts/kitchensink/manifests/sink-server.yaml

- Add object model
- Add lots of test data
- Add YAML processing API on top of k8s

feat(*): add object model for charts

---

docs/workspace.md

Based on a conversation with @gabrtv I wrote up this document explaining how the workspace is designed.

doc: add a document explaining the workspace directory

---

helm/action/create.go
helm/action/edit.go

fix(edit): construct correct abspath to skel directory

---

.gitignore

Test data should be checked into version control.
Missing data causing tests to fail in CI.  https://github.com/deis/helm/pull/58

fix(test): remove testdata from gitignore

---

README.md
docs/architecture.md
helm/action/publish.go
helm/helm.go

..for pushing charts from workspace to the repo checkout. Closes #56.

feat(publish): add publish command

---

helm/action/install.go

fix(*): add namespace to install command

---

helm/helm.go

Adds nice help text for cases where users specifies the wrong
number of arguments. How is this not already handled by
codegangsta/cli?

fix: handle argv counting

---

helm/action/update.go

Give a bit more info when running update.

feature(update) show local and remote info on update

---

Makefile
glide.yaml
helm/action/fetch.go
helm/action/info_test.go
helm/action/install.go
helm/action/print_readme.go
helm/dependency/dependency.go
helm/dependency/dependency_test.go
helm/helm.go
helm/testdata/charts/dep1/Chart.yaml
helm/testdata/charts/dep2/Chart.yaml
helm/testdata/charts/dep3/Chart.yaml
helm/testdata/charts/deptest/Chart.yaml

feat(*): add dependency resolution

---

helm/log/log.go
helm/prettyprint/colorizer.go
helm/prettyprint/colorizer_test.go

Colorize the output of helm commands

---

helm/action/update.go
helm/action/update_test.go
helm/helm.go

Point to the right chart location.
```
helm [chart-location*]$ ./bin/helm update
---> Creating /Users/jhansen/.helm
---> Creating /Users/jhansen/.helm/cache
---> Creating /Users/jhansen/.helm/workspace
---> Creating /Users/jhansen/.helm/cache/charts
---> Cloning repo into "/Users/jhansen/.helm/cache/charts". Please wait.
---> Updated /Users/jhansen/.helm/cache/charts from https://github.com/deis/charts
helm [chart-location*]$ ./bin/helm search alpine
--->
=================
---> Available Charts
---> =================
---> 	alpine (alpine-pod 0.0.1) - Simple pod running Alpine Linux.
--->
helm [chart-location*]$ ./bin/helm fetch alpine
---> Fetching /Users/jhansen/.helm/cache/charts/alpine to /Users/jhansen/.helm/workspace/charts/alpine
---> Copying /Users/jhansen/.helm/cache/charts/alpine …
```

fix(chart) charts moved

---

README.md

feat(README): adjust installing/using/building helm

---

helm/action/search.go
helm/action/search_test.go
helm/testdata/charts/searchtest1/Chart.yaml
helm/testdata/charts/searchtest2/Chart.yaml

feat(search): search chartfile name and description

---

README.md

docs(README): add glide version warning

---

helm.go

chore(update): add `helm up` alias for `helm update`

---

README.md
action/search.go

I plan to follow this up with cleanup of `helm info` and `helm install` output, with corresponding readme updates. Refs #116.

fix(search): cleanup search output and update readme

---

Makefile
action/create.go
action/fetch.go
action/info.go
action/install.go
action/list.go
action/search.go
action/uninstall.go
chart/chart.go
chart/chart_test.go
chart/chartfile.go
dependency/dependency.go
dependency/dependency_test.go

Fixes: https://github.com/deis/helm/issues/145

chore(*): rename `model` package to `chart`

---

action/uninstall.go

This PR fixes a race condition in the uninstall logic.  Pods must be deleted before RCs.  
Before this PR:
```console
$ helm install redis-cluster
---> No chart named "redis-cluster" in your workspace. Fetching now.
---> Running `kubectl create -f` ...
services/redis-sentinel
pods/redis-master
replicationcontrollers/redis
replicationcontrollers/redis-sentinel
---> Done
$ helm uninstall redis-cluster
---> Running `kubectl delete` ...
[WARN] Could not delete pod redis-master (Skipping): Error from server: pods "redis-master" not found
: exit status 1
---> Done
```
After this PR:
```console
$ helm install redis-cluster
---> No chart named "redis-cluster" in your workspace. Fetching now.
---> Running `kubectl create -f` ...
services/redis-sentinel
pods/redis-master …
```

fix(uninstall): delete pods before rcs to prevent race

---

action/fetch.go

fix(*): improve error handling on fetch

---

action/helper_test.go
action/info_test.go
action/remove_test.go
action/search_test.go
action/update_test.go

Fixes: https://github.com/deis/helm/issues/164

chore(tests): make update_test use a temp dir for home

---

README.md

docs(readme): add future plans section, cleanup language

---

README.md
action/install.go
helm.go

closes #78 
This is my first time contributing to Helm. Woo! Anything else I should add here? docs/tests?

feat(helm): add --dry-run flag to install

---

action/update_test.go
helm.go
release/latest.go
release/latest_test.go

fix(*): add no-version-check flag to update

---

README.md
docs/architecture.md

Align README and architecture with lightly modified cli output.

style(doc) align readme and architecture

---

README.md
docs/index.md

Few tweaks for the docs.
Expand requirements section, add flavor for https://helm.readthedocs.org/en/latest/

Documentation updates.

---

action/search.go
action/search_test.go

```console
$ helm search notalikelychartname
No chart found for "notalikelychartname".
```
Closes #181.

feat(action): report when no charts are found

---

docs/using_labels.md

fix(doc): add section on heritage label

---

Makefile
action/action.go
action/info.go
action/search.go
action/update.go
chart/chart.go
chart/chartfile.go
config/config.go
dependency/dependency.go
log/log.go
manifest/manifest.go
release/latest.go

Silences all the `golint` warnings that #168 started announcing.

style(*): add comments and linter cleanup

---

README.md
docs/index.md

docs(helm) adding links to the now-live helm.sh site

---

docs/awsome.md

This adds "How to write awesome charts"

docs(awesome): add awesome helm charts document

---

Makefile

First change in a series of Makefile improvements...

feat(Makefile): avoid enumerating variable contents

---

Makefile

- stop if GOPATH not set
- use variables that can be reused across goals

feat(Makefile): various Makefile improvements

---

action/install.go
chart/chart.go
codec/codec.go
codec/json.go
codec/json_test.go
codec/manifest.go
codec/manifest_test.go
codec/yaml.go
codec/yaml_test.go
manifest/manifest.go
testdata/pod.yaml
testdata/policy.json
testdata/rc.yaml
testdata/three-pods.yaml

The codec provides a faster and easier way of encoding and decoding
both YAML and JSON.

feat(*): add YAML/JSON codec

---

helm.go

fix(publish command): error, don't panic, when chart not specified

---

glide-full.yaml
glide.yaml

chore(glide-full.yaml): update the go-github version

---

action/install.go

fix(install): prevent -p from pointing to dest

---

action/uninstall.go
glide.yaml
helm.go
log/log.go

fix(uninstall): prompt for confirmation

---

action/fetch.go
chart/chartfile.go
chart/chartfile_test.go
codec/codec.go
dependency/dependency.go
dependency/dependency_test.go
docs/awsome.md
docs/workspace.md
testdata/charts/dep1/Chart.yaml
testdata/charts/dep2/Chart.yaml
testdata/charts/dep3/Chart.yaml

This addresses #209 and #213, and adds ability to constrain
dependencies based on repo, not just name and version.

feat(*): add from and repo for dependency resolve

---

helm.go

feat(rm): allow more than one chart removal

---

action/install.go
helm.go

fix(install): remove -p flag

---

action/install.go
action/remove_test.go
action/uninstall.go
chart/chart.go
codec/object.go
codec/object_test.go
testdata/charts/kitchensink/manifests/sink-serviceaccount.yaml
testdata/serviceaccount.yaml

fix(*): add support for ServiceAccount

---

README.md

This adds a note to tell 0.1 users how to update their charts repo
to 0.2.

docs(README): add note on helm/charts change

---

action/update_test.go
log/log.go

Fixes: https://github.com/helm/helm/issues/277

fix(log): print debug and warn messages to stderr

---

.travis.yml
Makefile

feat(Makefile): add golint to Makefile

---

helm.go

* standardize aliases as short form

feat(list): add ls alias

---

action/remove.go

Fixes: https://github.com/helm/helm/issues/285

fix(rm): remove missleading error on rm

---

CONTRIBUTING.md

Issue #265 suggests that we should have contribution guidelines that are
more specific to the Helm project. This adds a few high-level notes and
then points the user back to the Deis guidelines.

chore(CONTRIBUTING): explain contribution process

---

action/doctor.go
action/doctor_test.go
action/install.go
action/target.go
action/uninstall.go
action/update.go
action/update_test.go
helm.go

- move all prereq checks under the doctor umbrella

feat(doctor): add helm doctor command

---

action/search.go
action/search_test.go
helm.go
search/search.go
search/search_test.go

This addresses #287. It adds a search index and scoring.

feat(search): improve search feature

---

action/publish.go
config/config.go
helm.go

resolves: https://github.com/helm/helm/issues/288

feat(publish): publish to a specific repo

---

config/config.go
config/config_test.go

Fixes https://github.com/helm/helm/issues/229

feat(update): print summary of changes after helm update

---

action/action_test.go
action/target.go
action/target_test.go
helm.go
kubectl/cluster_info.go
kubectl/command.go
kubectl/create.go
kubectl/create_test.go
kubectl/delete.go
kubectl/get.go
kubectl/get_test.go
kubectl/kubectl.go
kubectl/kubectl_test.go

Starting to break up https://github.com/helm/helm/pull/264 into smaller chunks

ref(*): refactor kubectl to a package

---

config/config.go

Fixes: https://github.com/helm/helm/issues/328

fixes(update): check if chart repo is dirty before pulling

---

action/install.go

Fixes: https://github.com/helm/helm/issues/345
/cc @technosophos

fix(bug): print debug messages on install

---

config/config_test.go

Fixes: https://github.com/helm/helm/issues/340

fix(config, test): do not enforce order of summary in tests

---

cli/install.go

fix(cli): remove mention of removed --chart-path

---

util/helm.go

chore(logger): remove debug message in copy function

---

action/info_test.go
action/install_test.go
action/remove_test.go
action/repo_test.go
action/search_test.go
action/target_test.go
action/uninstall_test.go
action/update_test.go
test/helm.go

ref(tests): use test helpers in all unit tests

---

action/lint.go
action/lint_test.go
cli/lint.go
cli/lint_test.go

* accepts reference to chart in home directory or path
* remove useless flag test
* Fixes #311

feat(lint): lint by path

---

chart/chart_test.go
chart/chartfile.go
docs/awesome.md
testdata/charts/kitchensink/Chart.yaml
testdata/test-Chart.yaml

Closes https://github.com/helm/helm/issues/221

feat(chartfile): add source field

---

action/create.go
action/lint.go
action/lint_test.go
testdata/charts/misnamed/Chart.yaml

feat(lint.go): add check for chart name != directory name

---

action/lint.go

ref(lint): change vars to constants

---

action/action.go
action/repo.go

ref(repo): run helm doctor before failing

---

action/uninstall.go
action/uninstall_test.go

This is a stop gap fix for issue #392.

fix(uninstall): require the -n flag to be set

---

manifest/manifest.go
manifest/manifest_test.go
testdata/charts/malformed/Chart.yaml
testdata/charts/malformed/manifests/malformed.yaml

feat(manifest): identify which file failed to be parsed

---

action/generate.go
action/generate_test.go
action/install.go
action/template.go
action/template_test.go
cli/generate.go
cli/template.go
generator/generator.go
generator/generator_test.go
util/helm.go

The force flag only works for executing  helm template command in the helm generate header and helm template command directly

feat(generate): add force flag to overwrite generated template

---

docs/chart_tables.md
mkdocs.yml

This PR fixes issue #411 by adding chart_tables.md doc on additional repos and updates mkdocs.yaml to make sure it gets included in the read the docs site.

add doc on using additional repos and update read the docs config

---

.travis.yml

See https://github.com/Masterminds/glide/releases/tag/0.10.2

chore(.travis.yml): update glide to 0.10.2

---

README.md

chore(status): update readme to reflect helm/helm status

---

.travis.yml
Makefile

feat(containerize helm build): docker build for helm

---

Makefile

ref(helmc): Rename the uploaded binary files to start with helmc

---

action/install.go
action/remove_test.go
chart/chart_test.go
testdata/charts/kitchensink/manifests/sink-deployment.yaml

Added Deployment support to helm

---

docs/generate-and-template.md

Replaces #448. 
Thanks again @jhgaylor! I rebased your commit so we could add this to docs. Let me know if you have any concerns.

docs(generate-and-template): mention the env function

---

README.md

same fix as in https://github.com/deis/workflow-cli/pull/72
closes #485

doc(README): link to LICENSE
